### PR TITLE
Kernel improvements

### PR DESCRIPTION
**Pull request by WiZaRd981**
***Adreno idler => No more heat in videos
***Relaxed Governor => For those who don't play games, normal-usage users.

### CODE REVIEW

**Review by steadfasterX — COMMENTED** [review]
## Comment / Optional change request

### https://github.com/Suicide-Squirrel/Titan-Kernel-LG-G4/pull/41/commits/04417e2e8130e73defbc841b034204973386f0aa

nobody uses msm8994_defconfig in its device tree so this one is useless imho.
we can leave it here but as said..

**Review by steadfasterX — CHANGES_REQUESTED** [review]
## Merge conflict / Will not merge without a change/answer

### https://github.com/Suicide-Squirrel/Titan-Kernel-LG-G4/pull/41/commits/1c8fc0c5b0b8a7e8e370661c987294e94a38842d

where do you picked that from? there is no author in there

**Review by steadfasterX — CHANGES_REQUESTED** [review]
## Merge conflict / Will not merge without a change/answer

### https://github.com/Suicide-Squirrel/Titan-Kernel-LG-G4/pull/41/commits/fca0a6f20366166883619d0f68fdc655e48c3d6e

Author?
also the commit title is too long ;)

**Review by steadfasterX — COMMENTED** [review]
## Optional change request

### https://github.com/Suicide-Squirrel/Titan-Kernel-LG-G4/pull/41/commits/eae76ec0d9ab7968e4bdd50bb2a1c0d7d5dc4e43

I would prefer **not** having these lines:

```
> #####################
> #                   #
> #  Custom Features  #
> #                   #
> #####################
```

but I will merge if you insist on it

**Review by steadfasterX — COMMENTED** [review]
### https://github.com/Suicide-Squirrel/Titan-Kernel-LG-G4/pull/41/commits/ffbd275dc2a6bb37b984546cbc6b75ab48151e37

that's ok

**Review by steadfasterX — COMMENTED** [review]
### https://github.com/Suicide-Squirrel/Titan-Kernel-LG-G4/pull/41/commits/8a2117d41d8edefe2c399fd9a6157f8673a9a764

that's ok

**Review by steadfasterX — COMMENTED** [review]
### https://github.com/Suicide-Squirrel/Titan-Kernel-LG-G4/pull/41/commits/a3bdccf7b2844834ded9fc8acab61798ae360dc7

that's ok

**Review by steadfasterX — COMMENTED** [review]
### https://github.com/Suicide-Squirrel/Titan-Kernel-LG-G4/pull/41/commits/91dbb3da0800c218b5da7922168d0f7e075dfd00

that's ok

**Review by steadfasterX — COMMENTED** [review]
### https://github.com/Suicide-Squirrel/Titan-Kernel-LG-G4/pull/41/commits/e143178ef8ef56df9fa5dd84411c4eace22d8ebc

that's ok

**Review by steadfasterX — COMMENTED** [review]
### https://github.com/Suicide-Squirrel/Titan-Kernel-LG-G4/pull/41/commits/9fa2c09610b74ab4582fa2f14652261452be0a3f

that's ok

**Review by steadfasterX — COMMENTED** [review]
### https://github.com/Suicide-Squirrel/Titan-Kernel-LG-G4/pull/41/commits/9c16ea584fe5e522553910080b5a8b106643702e

that's ok

**Review by steadfasterX — COMMENTED** [review]
### https://github.com/Suicide-Squirrel/Titan-Kernel-LG-G4/pull/41/commits/eec0c279803de403a96292f9fa1eb7c672fcda32

that's ok

**Review by steadfasterX — COMMENTED** [review]
### https://github.com/Suicide-Squirrel/Titan-Kernel-LG-G4/pull/41/commits/8d58d07c813519057b16a0f6a9aebb5c1862048a

ugly and too long title (yea ik not your fault ;) )
so.. ok to keep it identical with the origin

**Review by steadfasterX — CHANGES_REQUESTED** [review]
## Merge conflict / Will not merge without a change/answer

### https://github.com/Suicide-Squirrel/Titan-Kernel-LG-G4/pull/41/commits/479e4a37b01162d37845e33759e6d3d60e7dd5ae

ok there are several things wrong with this commit:

1. wrong author
1. the title is too long
1. no information about what this is or how that helps (and for what)

**Review by steadfasterX — CHANGES_REQUESTED** [review]
## Merge conflict / Will not merge without a change/answer

### https://github.com/Suicide-Squirrel/Titan-Kernel-LG-G4/pull/41/commits/b8bf5b2ce57d2da4c9f281799e49052ecf7e5398

This one is problematic. I do not think it is a good idea to remove the default here. If you want to enable double-tap set it in the defconfigs but as we all know that the driver and implementation is faulty and causes a lot of battery drain I will keep the default to "No" here. Pls remove that one from your PR..

**Comment by pavlaras** [comment]
1. Do not add a governor only for h815. what about h811 and others ?
2. Instead of kanging the cpu boost, use cherry-pick and then edit the commit in order to keep the author please, otherwise this wont be merged.
3. Double tap here is useless. It only enables useless loops running in the background when this driver sadly only works with the LG closed display and power hal which we do not have. Remove that commit.
4. Re-implementing a half working tap 2 wake it only drains huge battery amounts. This won't make it unless you can write a code that fully works.

**Comment by WiZaRd981** [comment]
Adreno_Idler seems pretty unstable when phone is on idle.. Workload should be more tested, phone heating on Chrome and games are gone, but on idle, frequencies are changing every ms (180-300MhZ)
I didn't add double-tap support and cpu-boost implemention to PR, that's from January, didn't look what I want to PR, first time using GIT. 

P.S. Will add governors to more defconfigs, thanks for warnings.

**Comment by steadfasterX** [comment]
> Adreno_Idler seems pretty unstable when phone is on idle.. Workload should be more tested, phone heating on Chrome and games are gone, but on idle, frequencies are changing every ms (180-300MhZ)
> I didn't add double-tap support and cpu-boost implemention to PR, that's from January, didn't look what I want to PR, first time using GIT.
> 
> P.S. Will add governors to more defconfigs, thanks for warnings.

yea..

... and IMHO its better to really do a single PR for each feature/bug you wanna add/fix. That does **not** necessarily mean a PR for every _commit_ (so when a single feature needs multiple commits its fine to have it in 1 PR as long as they are related) but its not unlikely though.

so:

* a single PR to add the new governor CPU_FREQ_DEFAULT_GOV_RELAXED
* another PR for adding the adreno idler and its adjustments
* another PR to add a simple api to query the display state (and a bit explanation why it is needed/good to have)
* another PR to Implement touch boost configuration
* another PR to Enable pstore and its console

that way a review is incredible more simpler, easier to handle when changes happen, faster as 1 big PR with several features/bugfixes not related to each other would block a merge even when it contains changes which are fine to merge... 

 and its not much work on your site to do so:

just create a branch for each PR (e.g. **pr/add-gov-relaxed** or **pr_adreno-idler**,... - the actual name is up to you. choose something which helps you to identify for what it was meant for) and then do the PR based on that specific PR - branch.

When something needs to be adjusted later you can simply switch to that branch again, doing changes, pushing again and the PR gets updated.

Does that makes sense? If so pls close this PR and do accordingly .. thx for your work on this!

**Comment by pavlaras** [comment]
relaxed governor in 1 request.
adreno idler to another. And don't worry about stability on idle. i can fix that by adding only a few mV and it will be stable.
Just please 1 request for each thing

**Pull request closed without merging**
